document.addEventListener('DOMContentLoaded', function () {
  const lines = [
    { file: '/lines/2fast5me.mp3', line: '2fast5me' },
    { file: '/lines/99 luftballons.mp3', line: '99 luftballons' },
    { file: '/lines/aliens its got to be aliens.mp3', line: 'aliens its got to be aliens' },
    { file: '/lines/all out of cock cant restock.mp3', line: 'all out of cock cant restock' },
    {
      file: '/lines/all you had to do was follow the damn train cj.mp3',
      line: 'all you had to do was follow the damn train cj',
    },
    { file: '/lines/almost caught captain jack sparrow.mp3.mp3', line: 'almost caught captain jack sparrow.mp3' },
    { file: '/lines/america fuck yeah.mp3', line: 'america fuck yeah' },
    { file: '/lines/and dey say1.mp3', line: 'and dey say1' },
    { file: '/lines/and dey say2.mp3', line: 'and dey say2' },
    { file: '/lines/and dey say3.mp3', line: 'and dey say3' },
    { file: '/lines/and dey say4.mp3', line: 'and dey say4' },
    { file: '/lines/and dey say5.mp3', line: 'and dey say5' },
    { file: '/lines/and dey say6.mp3', line: 'and dey say6' },
    { file: '/lines/around the world.mp3', line: 'around the world' },
    { file: '/lines/ass we can.mp3', line: 'ass we can' },
    { file: '/lines/babag or fortnite.mp3', line: 'babag or fortnite' },
    { file: '/lines/back to the choppa.mp3', line: 'back to the choppa' },
    { file: '/lines/backstreet boys are back.mp3', line: 'backstreet boys are back' },
    { file: '/lines/bacon is good for me1.mp3', line: 'bacon is good for me1' },
    { file: '/lines/bacon is good for me2.mp3', line: 'bacon is good for me2' },
    { file: '/lines/bacon is good for me3.mp3', line: 'bacon is good for me3' },
    { file: '/lines/bacon is good for me4.mp3', line: 'bacon is good for me4' },
    { file: '/lines/bacon is good for me5.mp3', line: 'bacon is good for me5' },
    { file: '/lines/bacon is good for me6.mp3', line: 'bacon is good for me6' },
    { file: '/lines/bacon is good for us.mp3', line: 'bacon is good for us' },
    { file: '/lines/bad romance.mp3', line: 'bad romance' },
    { file: '/lines/bada bing bada boom1.mp3', line: 'bada bing bada boom1' },
    { file: '/lines/bada bing bada boom2.mp3', line: 'bada bing bada boom2' },
    { file: '/lines/bada bing bada boom3.mp3', line: 'bada bing bada boom3' },
    { file: '/lines/bada bing bada boom4.mp3', line: 'bada bing bada boom4' },
    { file: '/lines/battlefield theme.mp3', line: 'battlefield theme' },
    { file: '/lines/be our guest.mp3', line: 'be our guest' },
    { file: '/lines/be our guest2.mp3', line: 'be our guest2' },
    { file: '/lines/before i have to leave you now.mp3', line: 'before i have to leave you now' },
    { file: '/lines/best pirate.mp3', line: 'best pirate' },
    { file: '/lines/better call saul.mp3', line: 'better call saul' },
    { file: '/lines/big booty bitches1.mp3', line: 'big booty bitches1' },
    { file: '/lines/big booty bitches2.mp3', line: 'big booty bitches2' },
    { file: '/lines/bitconnect1.mp3', line: 'bitconnect1' },
    { file: '/lines/bitconnect2.mp3', line: 'bitconnect2' },
    { file: '/lines/boys boys boys1.mp3', line: 'boys boys boys1' },
    { file: '/lines/boys boys boys2.mp3', line: 'boys boys boys2' },
    { file: '/lines/but first let me take a selfie1.mp3', line: 'but first let me take a selfie1' },
    { file: '/lines/but first let me take a selfie2.mp3', line: 'but first let me take a selfie2' },
    { file: '/lines/but first let me take a selfie3.mp3', line: 'but first let me take a selfie3' },
    { file: '/lines/but first let me take a selfie4.mp3', line: 'but first let me take a selfie4' },
    { file: '/lines/but first let me take a selfie5.mp3', line: 'but first let me take a selfie5' },
    { file: '/lines/but looks can be deceiving.mp3', line: 'but looks can be deceiving' },
    { file: '/lines/but my body is telling me yes.mp3', line: 'but my body is telling me yes' },
    { file: '/lines/california here we come.mp3', line: 'california here we come' },
    { file: '/lines/call me maybe1.mp3', line: 'call me maybe1' },
    { file: '/lines/call me maybe2.mp3', line: 'call me maybe2' },
    { file: '/lines/captain jack sparrow.mp3', line: 'captain jack sparrow' },
    { file: '/lines/cash me outside.mp3', line: 'cash me outside' },
    { file: '/lines/cbt.mp3', line: 'cbt' },
    { file: '/lines/chandelier.mp3', line: 'chandelier' },
    { file: '/lines/charlie bit me.mp3', line: 'charlie bit me' },
    { file: '/lines/charlie bit me2.mp3', line: 'charlie bit me2' },
    { file: '/lines/charlie bit me3.mp3', line: 'charlie bit me3' },
    { file: '/lines/charlie that really hurt.mp3', line: 'charlie that really hurt' },
    { file: '/lines/china number 1.mp3', line: 'china number 1' },
    { file: '/lines/colonel bogey march.mp3', line: 'colonel bogey march' },
    { file: '/lines/cotton eye joe.mp3', line: 'cotton eye joe' },
    { file: '/lines/crash this plane with no survivors.mp3', line: 'crash this plane with no survivors' },
    { file: '/lines/crashing this plane with no survivors1.mp3', line: 'crashing this plane with no survivors1' },
    { file: '/lines/crashing this plane with no survivors2.mp3', line: 'crashing this plane with no survivors2' },
    { file: '/lines/crashing this plane with no survivors3.mp3', line: 'crashing this plane with no survivors3' },
    { file: '/lines/cunt with his arse out1.mp3', line: 'cunt with his arse out1' },
    { file: '/lines/cunt with his arse out2.mp3', line: 'cunt with his arse out2' },
    { file: '/lines/cut my life into pieces1.mp3', line: 'cut my life into pieces1' },
    { file: '/lines/cut my life into pieces2.mp3', line: 'cut my life into pieces2' },
    { file: '/lines/cut my life into pieces3.mp3', line: 'cut my life into pieces3' },
    { file: '/lines/cut my life into pieces4.mp3', line: 'cut my life into pieces4' },
    { file: '/lines/cut my wife into pieces.mp3', line: 'cut my wife into pieces' },
    { file: '/lines/damn son.mp3', line: 'damn son' },
    { file: '/lines/dancing in the moonlight.mp3', line: 'dancing in the moonlight' },
    { file: '/lines/danke.mp3', line: 'danke' },
    { file: '/lines/dedotated wam.mp3', line: 'dedotated wam' },
    { file: '/lines/deez nuts ha got em.mp3', line: 'deez nuts ha got em' },
    { file: '/lines/deez nuts.mp3', line: 'deez nuts' },
    { file: '/lines/despacito1.mp3', line: 'despacito1' },
    { file: '/lines/despacito2.mp3', line: 'despacito2' },
    { file: '/lines/despacito3.mp3', line: 'despacito3' },
    { file: '/lines/desperate times.mp3', line: 'desperate times' },
    { file: '/lines/dicks in my ass.mp3', line: 'dicks in my ass' },
    { file: '/lines/do the roar.mp3', line: 'do the roar' },
    { file: '/lines/do the roar2.mp3', line: 'do the roar2' },
    { file: '/lines/do you know da way.mp3', line: 'do you know da way' },
    { file: '/lines/do you know what it feels like.mp3', line: 'do you know what it feels like' },
    { file: '/lines/do you suck dicks.mp3', line: 'do you suck dicks' },
    { file: '/lines/doin your mom.mp3', line: 'doin your mom' },
    { file: '/lines/dont cry for me1.mp3', line: 'dont cry for me1' },
    { file: '/lines/dont cry for me2.mp3', line: 'dont cry for me2' },
    { file: '/lines/dont cry for me3.mp3', line: 'dont cry for me3' },
    { file: '/lines/dont cry for me4.mp3', line: 'dont cry for me4' },
    { file: '/lines/dont put the blame on me.mp3', line: 'dont put the blame on me' },
    { file: '/lines/double rainbow.mp3', line: 'double rainbow' },
    { file: '/lines/ducktails.mp3', line: 'ducktails' },
    { file: '/lines/duel of the fates.mp3', line: 'duel of the fates' },
    { file: '/lines/epic rap battles of history1.mp3', line: 'epic rap battles of history1' },
    { file: '/lines/epic rap battles of history2.mp3', line: 'epic rap battles of history2' },
    { file: '/lines/epic wutface battles of history.mp3', line: 'epic wutface battles of history' },
    { file: '/lines/even steven.mp3', line: 'even steven' },
    { file: '/lines/everybody in the nether knows kung fu.mp3', line: 'everybody in the nether knows kung fu' },
    { file: '/lines/everyday im shuffling.mp3', line: 'everyday im shuffling' },
    { file: '/lines/everyone get in here1.mp3', line: 'everyone get in here1' },
    { file: '/lines/everyone get in here2.mp3', line: 'everyone get in here2' },
    { file: '/lines/everyone get in here3.mp3', line: 'everyone get in here3' },
    { file: '/lines/eye of the tiger.mp3', line: 'eye of the tiger' },
    { file: '/lines/fisting is 300 bucks.mp3', line: 'fisting is 300 bucks' },
    { file: '/lines/for now.mp3', line: 'for now' },
    { file: '/lines/for you.mp3', line: 'for you' },
    { file: '/lines/forsen forsen im your number 1 fan1.mp3', line: 'forsen forsen im your number 1 fan1' },
    { file: '/lines/forsen forsen im your number 1 fan2.mp3', line: 'forsen forsen im your number 1 fan2' },
    { file: '/lines/forsen forsen im your number 1 fan3.mp3', line: 'forsen forsen im your number 1 fan3' },
    { file: '/lines/forsen forsen im your number 1 fan4.mp3', line: 'forsen forsen im your number 1 fan4' },
    { file: '/lines/friday.mp3', line: 'friday' },
    { file: '/lines/fuck it well do it live.mp3', line: 'fuck it well do it live' },
    { file: '/lines/fuck my ass and call me charlie.mp3', line: 'fuck my ass and call me charlie' },
    { file: '/lines/fuck my ass.mp3', line: 'fuck my ass' },
    { file: '/lines/fuck you dolphin.mp3', line: 'fuck you dolphin' },
    { file: '/lines/fus ro dah.mp3', line: 'fus ro dah' },
    { file: '/lines/gandalf.mp3', line: 'gandalf' },
    { file: '/lines/garrosh vs malforen.mp3', line: 'garrosh vs malforen' },
    { file: '/lines/gay fish.mp3', line: 'gay fish' },
    { file: '/lines/god of war.mp3', line: 'god of war' },
    { file: '/lines/golden legendary.mp3', line: 'golden legendary' },
    { file: '/lines/good news everyone.mp3', line: 'good news everyone' },
    { file: '/lines/grab a seat by the hearth.mp3', line: 'grab a seat by the hearth' },
    { file: '/lines/grape fruit technique.mp3', line: 'grape fruit technique' },
    { file: '/lines/grenade1.mp3', line: 'grenade1' },
    { file: '/lines/grenade2.mp3', line: 'grenade2' },
    { file: '/lines/ground beef1.mp3', line: 'ground beef1' },
    { file: '/lines/ground beef2.mp3', line: 'ground beef2' },
    { file: '/lines/hate us cuz they anus.mp3', line: 'hate us cuz they anus' },
    { file: '/lines/hello mathafaka.mp3', line: 'hello mathafaka' },
    { file: '/lines/hello1.mp3', line: 'hello1' },
    { file: '/lines/hello2.mp3', line: 'hello2' },
    { file: '/lines/help1.mp3', line: 'help1' },
    { file: '/lines/help2.mp3', line: 'help2' },
    { file: '/lines/hey arnold.mp3', line: 'hey arnold' },
    { file: '/lines/hey hey hey.mp3', line: 'hey hey hey' },
    { file: '/lines/hey marine1.mp3', line: 'hey marine1' },
    { file: '/lines/hey marine2.mp3', line: 'hey marine2' },
    { file: '/lines/hide your kids hide your wife.mp3', line: 'hide your kids hide your wife' },
    { file: '/lines/high noon1.mp3', line: 'high noon1' },
    { file: '/lines/high noon2.mp3', line: 'high noon2' },
    { file: '/lines/high noon3.mp3', line: 'high noon3' },
    { file: '/lines/high noon4.mp3', line: 'high noon4' },
    { file: '/lines/high noon5.mp3', line: 'high noon5' },
    { file: '/lines/high noon6.mp3', line: 'high noon6' },
    { file: '/lines/higher and higher baby.mp3', line: 'higher and higher baby' },
    { file: '/lines/hit me baby1.mp3', line: 'hit me baby1' },
    { file: '/lines/hit me baby2.mp3', line: 'hit me baby2' },
    { file: '/lines/hit me baby3.mp3', line: 'hit me baby3' },
    { file: '/lines/hold your horses1.mp3', line: 'hold your horses1' },
    { file: '/lines/hold your horses2.mp3', line: 'hold your horses2' },
    { file: '/lines/homeless1.mp3', line: 'homeless1' },
    { file: '/lines/homeless2.mp3', line: 'homeless2' },
    { file: '/lines/house of the rising sun.mp3', line: 'house of the rising sun' },
    { file: '/lines/houston we have a problem.mp3', line: 'houston we have a problem' },
    { file: '/lines/how can she slap me.mp3', line: 'how can she slap me' },
    { file: '/lines/how can she slap1.mp3', line: 'how can she slap1' },
    { file: '/lines/how can she slap2.mp3', line: 'how can she slap2' },
    { file: '/lines/how they butchered my boy.mp3', line: 'how they butchered my boy' },
    { file: '/lines/hugh mungus wot.mp3', line: 'hugh mungus wot' },
    { file: '/lines/i am a doggie.mp3', line: 'i am a doggie' },
    { file: '/lines/i am the one and only.mp3', line: 'i am the one and only' },
    { file: '/lines/i cant believe youve done this1.mp3', line: 'i cant believe youve done this1' },
    { file: '/lines/i cant believe youve done this2.mp3', line: 'i cant believe youve done this2' },
    { file: '/lines/i cant believe youve done this3.mp3', line: 'i cant believe youve done this3' },
    { file: '/lines/i cant go to yemen1.mp3', line: 'i cant go to yemen1' },
    { file: '/lines/i cant go to yemen2.mp3', line: 'i cant go to yemen2' },
    { file: '/lines/i cant.mp3', line: 'i cant' },
    { file: '/lines/i didnt hear no bell.mp3', line: 'i didnt hear no bell' },
    { file: '/lines/i didnt mean to make you cry.mp3', line: 'i didnt mean to make you cry' },
    { file: '/lines/i forgor.mp3', line: 'i forgor' },
    { file: '/lines/i like turtles.mp3', line: 'i like turtles' },
    { file: '/lines/i prefer men.mp3', line: 'i prefer men' },
    { file: '/lines/i remember when i lost my mind1.mp3', line: 'i remember when i lost my mind1' },
    { file: '/lines/i remember when i lost my mind2.mp3', line: 'i remember when i lost my mind2' },
    { file: '/lines/i remember when i lost my mind3.mp3', line: 'i remember when i lost my mind3' },
    { file: '/lines/i remember when i lost my mind4.mp3', line: 'i remember when i lost my mind4' },
    { file: '/lines/i still love you1.mp3', line: 'i still love you1' },
    { file: '/lines/i still love you2.mp3', line: 'i still love you2' },
    { file: '/lines/i still love you3.mp3', line: 'i still love you3' },
    { file: '/lines/i turned my self into a cucumber.mp3', line: 'i turned my self into a cucumber' },
    { file: '/lines/i turned myself into a pickle.mp3', line: 'i turned myself into a pickle' },
    {
      file: '/lines/i used to be an adventurer but then i took an arrow to the knee.mp3',
      line: 'i used to be an adventurer but then i took an arrow to the knee',
    },
    { file: '/lines/i will remember you1.mp3', line: 'i will remember you1' },
    { file: '/lines/i will remember you2.mp3', line: 'i will remember you2' },
    { file: '/lines/i will remember you3.mp3', line: 'i will remember you3' },
    { file: '/lines/i will remember you4.mp3', line: 'i will remember you4' },
    { file: '/lines/i will remember you5.mp3', line: 'i will remember you5' },
    { file: '/lines/i will remember you6.mp3', line: 'i will remember you6' },
    { file: '/lines/i will remember you7.mp3', line: 'i will remember you7' },
    { file: '/lines/i will survive.mp3', line: 'i will survive' },
    { file: '/lines/ichiban lipstick for men.mp3', line: 'ichiban lipstick for men' },
    { file: '/lines/idk kev1.mp3', line: 'idk kev1' },
    { file: '/lines/idk kev2.mp3', line: 'idk kev2' },
    { file: '/lines/if you think you can graduate.mp3', line: 'if you think you can graduate' },
    { file: '/lines/ill give you what you want.mp3', line: 'ill give you what you want' },
    { file: '/lines/im a believer.mp3', line: 'im a believer' },
    { file: '/lines/im batman1.mp3', line: 'im batman1' },
    { file: '/lines/im batman2.mp3', line: 'im batman2' },
    { file: '/lines/im batman3.mp3', line: 'im batman3' },
    { file: '/lines/im bringing sexy back.mp3', line: 'im bringing sexy back' },
    { file: '/lines/im bringing sexy back2.mp3', line: 'im bringing sexy back2' },
    { file: '/lines/im hashem lo yivneh bayis.mp3', line: 'im hashem lo yivneh bayis' },
    { file: '/lines/im lovin it.mp3', line: 'im lovin it' },
    { file: '/lines/im undead not dead dead.mp3', line: 'im undead not dead dead' },
    { file: '/lines/im walking here.mp3', line: 'im walking here' },
    { file: '/lines/im walking on shitsand(sun shine).mp3', line: 'im walking on shitsand(sun shine)' },
    { file: '/lines/immigrant song.mp3', line: 'immigrant song' },
    { file: '/lines/immigrant song2.mp3', line: 'immigrant song2' },
    { file: '/lines/in game how.mp3', line: 'in game how' },
    { file: '/lines/indiana jones.mp3', line: 'indiana jones' },
    { file: '/lines/is it me youre looking for.mp3', line: 'is it me youre looking for' },
    { file: '/lines/is this real life.mp3', line: 'is this real life' },
    { file: '/lines/it aint easy.mp3', line: 'it aint easy' },
    { file: '/lines/it do go down.mp3', line: 'it do go down' },
    { file: '/lines/it do go down2.mp3', line: 'it do go down2' },
    { file: '/lines/it do go down3.mp3', line: 'it do go down3' },
    { file: '/lines/it do go down4.mp3', line: 'it do go down4' },
    { file: '/lines/it doesnt even matter.mp3', line: 'it doesnt even matter' },
    { file: '/lines/it is what it is.mp3', line: 'it is what it is' },
    { file: '/lines/its a me.mp3', line: 'its a me' },
    {
      file: '/lines/its beginning to look a lot like christmas.mp3',
      line: 'its beginning to look a lot like christmas',
    },
    { file: '/lines/its like a 3rd party thing.mp3', line: 'its like a 3rd party thing' },
    { file: '/lines/its morbin time.mp3', line: 'its morbin time' },
    { file: '/lines/its ova1.mp3', line: 'its ova1' },
    { file: '/lines/its ova2.mp3', line: 'its ova2' },
    { file: '/lines/its ova3.mp3', line: 'its ova3' },
    { file: '/lines/its over anakin.mp3', line: 'its over anakin' },
    { file: '/lines/its so fucking deep.mp3', line: 'its so fucking deep' },
    { file: '/lines/ive never seen a woman.mp3', line: 'ive never seen a woman' },
    { file: '/lines/jaws theme.mp3', line: 'jaws theme' },
    { file: '/lines/jizz in your pants.mp3', line: 'jizz in your pants' },
    { file: '/lines/joe biden you have 2 yil.mp3', line: 'joe biden you have 2 yil' },
    { file: '/lines/killing machine.mp3', line: 'killing machine' },
    { file: '/lines/killing me softly with his words.mp3', line: 'killing me softly with his words' },
    { file: '/lines/king of the castle.mp3', line: 'king of the castle' },
    { file: '/lines/king of the mountain very nice.mp3', line: 'king of the mountain very nice' },
    { file: '/lines/kitty cat dance.mp3', line: 'kitty cat dance' },
    { file: '/lines/ku menangis.mp3', line: 'ku menangis' },
    { file: '/lines/laser1.mp3', line: 'laser1' },
    { file: '/lines/laser2.mp3', line: 'laser2' },
    { file: '/lines/laser3.mp3', line: 'laser3' },
    { file: '/lines/last christmas1.mp3', line: 'last christmas1' },
    { file: '/lines/last christmas2.mp3', line: 'last christmas2' },
    { file: '/lines/leave britney alone.mp3', line: 'leave britney alone' },
    { file: '/lines/leave me alone.mp3', line: 'leave me alone' },
    { file: '/lines/legend wait for it ary.mp3', line: 'legend wait for it ary' },
    { file: '/lines/let me smell yo dick1.mp3', line: 'let me smell yo dick1' },
    { file: '/lines/let me smell yo dick2.mp3', line: 'let me smell yo dick2' },
    { file: '/lines/let me smell yo dick3.mp3', line: 'let me smell yo dick3' },
    { file: '/lines/let me smell yo dick4.mp3', line: 'let me smell yo dick4' },
    { file: '/lines/lets get right into the news.mp3', line: 'lets get right into the news' },
    { file: '/lines/life is like a box of chocolate.mp3', line: 'life is like a box of chocolate' },
    { file: '/lines/lion king.mp3', line: 'lion king' },
    { file: '/lines/look at this photograph.mp3', line: 'look at this photograph' },
    { file: '/lines/look at this photograph2.mp3', line: 'look at this photograph2' },
    {
      file: '/lines/lordy lord theres a fire i didnt grab no shoes or nothing.mp3',
      line: 'lordy lord theres a fire i didnt grab no shoes or nothing',
    },
    { file: '/lines/make your own kind of music.mp3', line: 'make your own kind of music' },
    {
      file: '/lines/master master wheres the dreams that ive been after.mp3',
      line: 'master master wheres the dreams that ive been after',
    },
    { file: '/lines/mathafaka mathafaka1.mp3', line: 'mathafaka mathafaka1' },
    { file: '/lines/mathafaka mathafaka2.mp3', line: 'mathafaka mathafaka2' },
    { file: '/lines/mathafaka mathafaka3.mp3', line: 'mathafaka mathafaka3' },
    { file: '/lines/mathafaka mathafaka4.mp3', line: 'mathafaka mathafaka4' },
    { file: '/lines/meep meep.mp3', line: 'meep meep' },
    { file: '/lines/moms spaghetti.mp3', line: 'moms spaghetti' },
    { file: '/lines/mr sandman.mp3', line: 'mr sandman' },
    { file: '/lines/mthafaka.mp3', line: 'mthafaka' },
    { file: '/lines/my life is not even potato.mp3', line: 'my life is not even potato' },
    {
      file: '/lines/my milkshake brings all the boys to the yard.mp3',
      line: 'my milkshake brings all the boys to the yard',
    },
    { file: '/lines/my name is boxxy.mp3', line: 'my name is boxxy' },
    { file: '/lines/my name is jeff.mp3', line: 'my name is jeff' },
    { file: '/lines/my name is jeff2.mp3', line: 'my name is jeff2' },
    { file: '/lines/my spider senses are tingling.mp3', line: 'my spider senses are tingling' },
    { file: '/lines/never say never1.mp3', line: 'never say never1' },
    { file: '/lines/never say never2.mp3', line: 'never say never2' },
    { file: '/lines/nintendo 64 1.mp3', line: 'nintendo 64 1' },
    { file: '/lines/nintendo 64 2.mp3', line: 'nintendo 64 2' },
    { file: '/lines/nintendo 64 3.mp3', line: 'nintendo 64 3' },
    { file: '/lines/no longer potato.mp3', line: 'no longer potato' },
    { file: '/lines/no one cared until he put on the mask.mp3', line: 'no one cared until he put on the mask' },
    { file: '/lines/no spammarino.mp3', line: 'no spammarino' },
    { file: '/lines/not the bees.mp3', line: 'not the bees' },
    { file: '/lines/nothing here1.mp3', line: 'nothing here1' },
    { file: '/lines/nothing here2.mp3', line: 'nothing here2' },
    { file: '/lines/nothing here3.mp3', line: 'nothing here3' },
    { file: '/lines/nothing here4.mp3', line: 'nothing here4' },
    { file: '/lines/obamas elf1.mp3', line: 'obamas elf1' },
    { file: '/lines/obamas elf2.mp3', line: 'obamas elf2' },
    { file: '/lines/ocean man.mp3', line: 'ocean man' },
    { file: '/lines/oh shit im sorry sorry for what.mp3', line: 'oh shit im sorry sorry for what' },
    { file: '/lines/one more time.mp3', line: 'one more time' },
    { file: '/lines/order.mp3', line: 'order' },
    { file: '/lines/out of my ass into your ass tonight1.mp3', line: 'out of my ass into your ass tonight1' },
    { file: '/lines/out of my ass into your ass tonight2.mp3', line: 'out of my ass into your ass tonight2' },
    { file: '/lines/over 9000.mp3', line: 'over 9000' },
    { file: '/lines/pains overlaod.mp3', line: 'pains overlaod' },
    { file: '/lines/part of where im going1.mp3', line: 'part of where im going1' },
    { file: '/lines/part of where im going2.mp3', line: 'part of where im going2' },
    { file: '/lines/part of where im going3.mp3', line: 'part of where im going3' },
    { file: '/lines/part of where im going4.mp3', line: 'part of where im going4' },
    { file: '/lines/part of where im going5.mp3', line: 'part of where im going5' },
    { file: '/lines/part of where im going6.mp3', line: 'part of where im going6' },
    { file: '/lines/part of where im going7.mp3', line: 'part of where im going7' },
    { file: '/lines/pepega1.mp3', line: 'pepega1' },
    { file: '/lines/pepega2.mp3', line: 'pepega2' },
    { file: '/lines/pepsi man.mp3', line: 'pepsi man' },
    { file: '/lines/pingu.mp3', line: 'pingu' },
    { file: '/lines/polska gurom.mp3', line: 'polska gurom' },
    { file: '/lines/potato1.mp3', line: 'potato1' },
    { file: '/lines/potato2.mp3', line: 'potato2' },
    { file: '/lines/potato3.mp3', line: 'potato3' },
    { file: '/lines/potato4.mp3', line: 'potato4' },
    { file: '/lines/potato5.mp3', line: 'potato5' },
    { file: '/lines/potatooo.mp3', line: 'potatooo' },
    { file: '/lines/pretty much everywhere its gonna be hot.mp3', line: 'pretty much everywhere its gonna be hot' },
    { file: '/lines/previously on lost1.mp3', line: 'previously on lost1' },
    { file: '/lines/previously on lost10.mp3', line: 'previously on lost10' },
    { file: '/lines/previously on lost2.mp3', line: 'previously on lost2' },
    { file: '/lines/previously on lost3.mp3', line: 'previously on lost3' },
    { file: '/lines/previously on lost4.mp3', line: 'previously on lost4' },
    { file: '/lines/previously on lost5.mp3', line: 'previously on lost5' },
    { file: '/lines/previously on lost6.mp3', line: 'previously on lost6' },
    { file: '/lines/previously on lost7.mp3', line: 'previously on lost7' },
    { file: '/lines/previously on lost8.mp3', line: 'previously on lost8' },
    { file: '/lines/previously on lost9.mp3', line: 'previously on lost9' },
    { file: '/lines/previously on prison break.mp3', line: 'previously on prison break' },
    { file: '/lines/previously on the grudge.mp3', line: 'previously on the grudge' },
    { file: '/lines/previously on the walking dead.mp3', line: 'previously on the walking dead' },
    { file: '/lines/professor carr.mp3', line: 'professor carr' },
    { file: '/lines/professor carr2.mp3', line: 'professor carr2' },
    { file: '/lines/push it to the limit.mp3', line: 'push it to the limit' },
    { file: '/lines/quite impressive.mp3', line: 'quite impressive' },
    { file: '/lines/rappers delight.mp3', line: 'rappers delight' },
    { file: '/lines/raul.mp3', line: 'raul' },
    { file: '/lines/README.md', line: 'README.md' },
    { file: '/lines/real human being.mp3', line: 'real human being' },
    { file: '/lines/reigns from heaven above1.mp3', line: 'reigns from heaven above1' },
    { file: '/lines/reigns from heaven above2.mp3', line: 'reigns from heaven above2' },
    {
      file: '/lines/remember this as the day where you almost beat captain jack sparrow.mp3',
      line: 'remember this as the day where you almost beat captain jack sparrow',
    },
    { file: '/lines/rickroll1.mp3', line: 'rickroll1' },
    { file: '/lines/rickroll2.mp3', line: 'rickroll2' },
    { file: '/lines/risk it for the biscuit1.mp3', line: 'risk it for the biscuit1' },
    { file: '/lines/risk it for the biscuit2.mp3', line: 'risk it for the biscuit2' },
    { file: '/lines/risk it for the biscuit3.mp3', line: 'risk it for the biscuit3' },
    { file: '/lines/risk it for the biscuit4.mp3', line: 'risk it for the biscuit4' },
    { file: '/lines/risk it for the biscuit5.mp3', line: 'risk it for the biscuit5' },
    { file: '/lines/rotten potato.mp3', line: 'rotten potato' },
    { file: '/lines/round 2 fight.mp3', line: 'round 2 fight' },
    { file: '/lines/ruined.mp3', line: 'ruined' },
    { file: '/lines/samir youre breaking the car.mp3', line: 'samir youre breaking the car' },
    { file: '/lines/say hello to my little friend1.mp3', line: 'say hello to my little friend1' },
    { file: '/lines/say hello to my little friend2.mp3', line: 'say hello to my little friend2' },
    { file: '/lines/say hello to my little friend3.mp3', line: 'say hello to my little friend3' },
    { file: '/lines/say something im giving up on you.mp3', line: 'say something im giving up on you' },
    { file: '/lines/scanning parameter.mp3', line: 'scanning parameter' },
    { file: '/lines/see you later alligator.mp3', line: 'see you later alligator' },
    { file: '/lines/sent out here to do a story.mp3', line: 'sent out here to do a story' },
    { file: '/lines/shit in my asshole.mp3', line: 'shit in my asshole' },
    { file: '/lines/shite without flushing.mp3', line: 'shite without flushing' },
    { file: '/lines/shoulda walked away.mp3', line: 'shoulda walked away' },
    { file: '/lines/shoulda woulda coulda.mp3', line: 'shoulda woulda coulda' },
    { file: '/lines/shungite.mp3', line: 'shungite' },
    { file: '/lines/shut up meg.mp3', line: 'shut up meg' },
    { file: '/lines/skater girl.mp3', line: 'skater girl' },
    { file: '/lines/skidiki pap pap and a pu pu pudrrr boom.mp3', line: 'skidiki pap pap and a pu pu pudrrr boom' },
    { file: '/lines/skidiki pap pap.mp3', line: 'skidiki pap pap' },
    { file: '/lines/slice em up doc.mp3', line: 'slice em up doc' },
    { file: '/lines/smack that.mp3', line: 'smack that' },
    { file: '/lines/smoke weed everyday1.mp3', line: 'smoke weed everyday1' },
    { file: '/lines/smoke weed everyday2.mp3', line: 'smoke weed everyday2' },
    { file: '/lines/snakes on a plane.mp3', line: 'snakes on a plane' },
    { file: '/lines/sneaky snitch.mp3', line: 'sneaky snitch' },
    { file: '/lines/somebody that i used to know1.mp3', line: 'somebody that i used to know1' },
    { file: '/lines/somebody that i used to know2.mp3', line: 'somebody that i used to know2' },
    { file: '/lines/somebody that i used to know3.mp3', line: 'somebody that i used to know3' },
    { file: '/lines/somebody that i used to know4.mp3', line: 'somebody that i used to know4' },
    { file: '/lines/somebody that i used to know5.mp3', line: 'somebody that i used to know5' },
    { file: '/lines/somebody that i used to know6.mp3', line: 'somebody that i used to know6' },
    { file: '/lines/somebody that i used to know7.mp3', line: 'somebody that i used to know7' },
    { file: '/lines/somebodys watching me.mp3', line: 'somebodys watching me' },
    { file: '/lines/somebodys watching me2.mp3', line: 'somebodys watching me2' },
    {
      file: '/lines/spamming those little baby precious emotes.mp3',
      line: 'spamming those little baby precious emotes',
    },
    { file: '/lines/spartans lower your weapons.mp3', line: 'spartans lower your weapons' },
    { file: '/lines/spartans what is your profession.mp3', line: 'spartans what is your profession' },
    { file: '/lines/speak vietnamese1.mp3', line: 'speak vietnamese1' },
    { file: '/lines/speak vietnamese2.mp3', line: 'speak vietnamese2' },
    { file: '/lines/speak vietnamese3.mp3', line: 'speak vietnamese3' },
    { file: '/lines/starting tom cruise.mp3', line: 'starting tom cruise' },
    { file: '/lines/stayin alive1.mp3', line: 'stayin alive1' },
    { file: '/lines/stayin alive2.mp3', line: 'stayin alive2' },
    { file: '/lines/stop spamming my laptop is getting hot.mp3', line: 'stop spamming my laptop is getting hot' },
    { file: '/lines/stupid fucking mistakes man.mp3', line: 'stupid fucking mistakes man' },
    { file: '/lines/take everything from the inside.mp3', line: 'take everything from the inside' },
    { file: '/lines/take me to church.mp3', line: 'take me to church' },
    { file: '/lines/tazdingo.mp3', line: 'tazdingo' },
    { file: '/lines/teenage mutant ninja turtles.mp3', line: 'teenage mutant ninja turtles' },
    { file: '/lines/thank you for coming to my ted talk.mp3', line: 'thank you for coming to my ted talk' },
    { file: '/lines/thanks for watching the stream.mp3', line: 'thanks for watching the stream' },
    { file: '/lines/that is legitness.mp3', line: 'that is legitness' },
    { file: '/lines/thats all she wrote.mp3', line: 'thats all she wrote' },
    { file: '/lines/thats just the way the cookie crumbles.mp3', line: 'thats just the way the cookie crumbles' },
    {
      file: '/lines/the fuck did you just say to me you little shit.mp3',
      line: 'the fuck did you just say to me you little shit',
    },
    { file: '/lines/the semen arsonist.mp3', line: 'the semen arsonist' },
    { file: '/lines/there we go master bruce1.mp3', line: 'there we go master bruce1' },
    { file: '/lines/there we go master bruce2.mp3', line: 'there we go master bruce2' },
    { file: '/lines/they see me hattin.mp3', line: 'they see me hattin' },
    { file: '/lines/they see me maldin.mp3', line: 'they see me maldin' },
    { file: '/lines/they see me rollin1.mp3', line: 'they see me rollin1' },
    { file: '/lines/they see me rollin2.mp3', line: 'they see me rollin2' },
    { file: '/lines/theyre taking the hobbits to isengard1.mp3', line: 'theyre taking the hobbits to isengard1' },
    { file: '/lines/theyre taking the hobbits to isengard2.mp3', line: 'theyre taking the hobbits to isengard2' },
    { file: '/lines/thingy majinggy1.mp3', line: 'thingy majinggy1' },
    { file: '/lines/thingy majinggy2.mp3', line: 'thingy majinggy2' },
    { file: '/lines/third party things.mp3', line: 'third party things' },
    { file: '/lines/this is not how the cookie crumbles.mp3', line: 'this is not how the cookie crumbles' },
    { file: '/lines/throat singing.mp3', line: 'throat singing' },
    { file: '/lines/too soon executus.mp3', line: 'too soon executus' },
    { file: '/lines/toss a coin1.mp3', line: 'toss a coin1' },
    { file: '/lines/toss a coin2.mp3', line: 'toss a coin2' },
    { file: '/lines/trololol.mp3', line: 'trololol' },
    { file: '/lines/turn down for what.mp3', line: 'turn down for what' },
    { file: '/lines/turn off the notifications.mp3', line: 'turn off the notifications' },
    { file: '/lines/umbrella.mp3', line: 'umbrella' },
    { file: '/lines/use the shovel chance.mp3', line: 'use the shovel chance' },
    { file: '/lines/used to be an adventurer1.mp3', line: 'used to be an adventurer1' },
    { file: '/lines/vape nation1.mp3', line: 'vape nation1' },
    { file: '/lines/vape nation2.mp3', line: 'vape nation2' },
    { file: '/lines/video killed the radio star.mp3', line: 'video killed the radio star' },
    { file: '/lines/wadu hek1.mp3', line: 'wadu hek1' },
    { file: '/lines/wadu hek2.mp3', line: 'wadu hek2' },
    { file: '/lines/wadu hek3.mp3', line: 'wadu hek3' },
    { file: '/lines/wadu hek4.mp3', line: 'wadu hek4' },
    { file: '/lines/war never changes.mp3', line: 'war never changes' },
    { file: '/lines/watch your profanity.mp3', line: 'watch your profanity' },
    { file: '/lines/wazzap.mp3', line: 'wazzap' },
    { file: '/lines/we could have had it all.mp3', line: 'we could have had it all' },
    { file: '/lines/we could have had it all2.mp3', line: 'we could have had it all2' },
    { file: '/lines/welcome to uganda.mp3', line: 'welcome to uganda' },
    { file: '/lines/well see well see1.mp3', line: 'well see well see1' },
    { file: '/lines/well see well see2.mp3', line: 'well see well see2' },
    { file: '/lines/well see well see3.mp3', line: 'well see well see3' },
    { file: '/lines/well see well see4.mp3', line: 'well see well see4' },
    { file: '/lines/well see well see5.mp3', line: 'well see well see5' },
    { file: '/lines/well see well see6.mp3', line: 'well see well see6' },
    { file: '/lines/well see well see7.mp3', line: 'well see well see7' },
    { file: '/lines/well see well see8.mp3', line: 'well see well see8' },
    { file: '/lines/well see well see9.mp3', line: 'well see well see9' },
    { file: '/lines/were about to find out1.mp3', line: 'were about to find out1' },
    { file: '/lines/were about to find out2.mp3', line: 'were about to find out2' },
    { file: '/lines/what are those.mp3', line: 'what are those' },
    { file: '/lines/what are you doing in me swamp.mp3', line: 'what are you doing in me swamp' },
    {
      file: '/lines/what are you trying to say that i can dodge bullets.mp3',
      line: 'what are you trying to say that i can dodge bullets',
    },
    {
      file: '/lines/what are you trying to tell me that i can dodge bullets1.mp3',
      line: 'what are you trying to tell me that i can dodge bullets1',
    },
    {
      file: '/lines/what are you trying to tell me that i can dodge bullets2.mp3',
      line: 'what are you trying to tell me that i can dodge bullets2',
    },
    {
      file: '/lines/what are you trying to tell me that i can dodge bullets3.mp3',
      line: 'what are you trying to tell me that i can dodge bullets3',
    },
    {
      file: '/lines/what did you say about me you little bitch.mp3',
      line: 'what did you say about me you little bitch',
    },
    { file: '/lines/what do you mean.mp3', line: 'what do you mean' },
    { file: '/lines/what does that mean for the future.mp3', line: 'what does that mean for the future' },
    { file: '/lines/what does the fox say1.mp3', line: 'what does the fox say1' },
    { file: '/lines/what does the fox say2.mp3', line: 'what does the fox say2' },
    { file: '/lines/what does the fox say3.mp3', line: 'what does the fox say3' },
    { file: '/lines/what doesnt kill you makes you stronger.mp3', line: 'what doesnt kill you makes you stronger' },
    { file: '/lines/whatcha talkin bout willis1.mp3', line: 'whatcha talkin bout willis1' },
    { file: '/lines/whatcha talkin bout willis2.mp3', line: 'whatcha talkin bout willis2' },
    { file: '/lines/whatcha talkin bout willis3.mp3', line: 'whatcha talkin bout willis3' },
    { file: '/lines/whatcha talkin bout willis4.mp3', line: 'whatcha talkin bout willis4' },
    { file: '/lines/whatcha talkin bout willis5.mp3', line: 'whatcha talkin bout willis5' },
    { file: '/lines/whatcha talkin bout willis6.mp3', line: 'whatcha talkin bout willis6' },
    { file: '/lines/whatcha talkin bout willis7.mp3', line: 'whatcha talkin bout willis7' },
    {
      file: '/lines/whats the most you ever lost in a coin toss.mp3',
      line: 'whats the most you ever lost in a coin toss',
    },
    { file: '/lines/when it rains it pours.mp3', line: 'when it rains it pours' },
    { file: '/lines/when the moon hits the sky1.mp3', line: 'when the moon hits the sky1' },
    { file: '/lines/when the moon hits the sky2.mp3', line: 'when the moon hits the sky2' },
    { file: '/lines/when you try your best1.mp3', line: 'when you try your best1' },
    { file: '/lines/when you try your best2.mp3', line: 'when you try your best2' },
    { file: '/lines/where are my dragons1.mp3', line: 'where are my dragons1' },
    { file: '/lines/where are my dragons2.mp3', line: 'where are my dragons2' },
    { file: '/lines/where are my dragons3.mp3', line: 'where are my dragons3' },
    { file: '/lines/where are my dragons4.mp3', line: 'where are my dragons4' },
    { file: '/lines/where are my dragons5.mp3', line: 'where are my dragons5' },
    { file: '/lines/where do we go now1.mp3', line: 'where do we go now1' },
    { file: '/lines/where do we go now2.mp3', line: 'where do we go now2' },
    { file: '/lines/where is rachel1.mp3', line: 'where is rachel1' },
    { file: '/lines/where is rachel2.mp3', line: 'where is rachel2' },
    { file: '/lines/where is she where is rachel.mp3', line: 'where is she where is rachel' },
    { file: '/lines/where is she.mp3', line: 'where is she' },
    { file: '/lines/where the fuck i am.mp3', line: 'where the fuck i am' },
    { file: '/lines/who wants to be a millionaire.mp3', line: 'who wants to be a millionaire' },
    { file: '/lines/whos that pokemon.mp3', line: 'whos that pokemon' },
    { file: '/lines/whos that pokemon2.mp3', line: 'whos that pokemon2' },
    { file: '/lines/why are you gay.mp3', line: 'why are you gay' },
    { file: '/lines/why are you runnin.mp3', line: 'why are you runnin' },
    { file: '/lines/why you always lying.mp3', line: 'why you always lying' },
    { file: '/lines/with great powers.mp3', line: 'with great powers' },
    { file: '/lines/with or without you.mp3', line: 'with or without you' },
    { file: '/lines/wombo combo that aint falco.mp3', line: 'wombo combo that aint falco' },
    { file: '/lines/wotah1.mp3', line: 'wotah1' },
    { file: '/lines/wotah2.mp3', line: 'wotah2' },
    { file: '/lines/wotah3.mp3', line: 'wotah3' },
    { file: '/lines/wotah4.mp3', line: 'wotah4' },
    { file: '/lines/yeah but thats like a third party thing.mp3', line: 'yeah but thats like a third party thing' },
    { file: '/lines/yolo1.mp3', line: 'yolo1' },
    { file: '/lines/yolo2.mp3', line: 'yolo2' },
    { file: '/lines/yolo3.mp3', line: 'yolo3' },
    { file: '/lines/you face jaraxxus.mp3', line: 'you face jaraxxus' },
    { file: '/lines/you never know1.mp3', line: 'you never know1' },
    { file: '/lines/you never know2.mp3', line: 'you never know2' },
    { file: '/lines/you never know3.mp3', line: 'you never know3' },
    { file: '/lines/you only yolo once.mp3', line: 'you only yolo once' },
    { file: '/lines/you shall not pass1.mp3', line: 'you shall not pass1' },
    { file: '/lines/you shall not pass2.mp3', line: 'you shall not pass2' },
    { file: '/lines/you shall not pass3.mp3', line: 'you shall not pass3' },
    { file: '/lines/you spin my head1.mp3', line: 'you spin my head1' },
    { file: '/lines/you spin my head2.mp3', line: 'you spin my head2' },
    { file: '/lines/youll never see me again.mp3', line: 'youll never see me again' },
    { file: '/lines/youre killing me lisa.mp3', line: 'youre killing me lisa' },
    { file: '/lines/youre telling me.mp3', line: 'youre telling me' },
    { file: '/lines/zamina mina1.mp3', line: 'zamina mina1' },
    { file: '/lines/zamina mina2.mp3', line: 'zamina mina2' },
    { file: '/lines/zero to hero.mp3', line: 'zero to hero' },
  ];
  document.getElementById('randomLineButton').addEventListener('click', function () {
    const randomLine = lines[Math.floor(Math.random() * lines.length)];
    let audio = new Audio(randomLine.file);
    audio.play();
    document.getElementById('randomLineContainer').textContent = randomLine.line;
  });
});
